services:
  frontend:
    container_name: frontend-container
    build:
      context: ../ORSProject-10-UI   # ✅ important
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    container_name: backend-container
    build:
      context: .   # ✅ important
    ports:
      - "8081:8081"   # ✅ correct
    depends_on:
      - mysql

  mysql:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orsproject10
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
